config/routes.rb
Rails.application.routes.draw do

  resources :pacientes
  resources :sugerencia
  resources :obra_socials
  resources :turnos
  
  devise_for :users
  
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end

  root 'site#index'

end

app/models/turno.rb
class Turno < ActiveRecord::Base
    
    
    belongs_to :user
    belongs_to :paciente
    
    #validates :date, presence: true
    
    
end

app/controllers/turno_controller.rb
class TurnoController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /pacientes
  # GET /pacientes.json
  def index
    @turnos = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @turno = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @turno = Paciente.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @turno.update(paciente_params)
        format.html { redirect_to @turno, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turno_params
      params.require(:turno).permit(:id_paciente, :id_usuario, :hora, :dia)
    end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turno_params
      params.require(:turno).permit(:user_id, :paciente_id, :hora, :dia)
    end
end

app/helpers/turno_helper.rb
module TurnoHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/turnos/_form.html.erb
<%= simple_form_for(@turno) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id_user %>
    <%= f.input :id_paciente %>
    <%= f.input :hora %>
    <%= f.input :dia %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<h1>Editing Turno</h1>

<%= render 'form' %>

<%= link_to 'Show', @turno %> |
<%= link_to 'Back', turnos_path %>

app/views/turnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Turnos</h1>

<table>
  <thead>
    <tr>
      <th>Id usuario</th>
      <th>Id paciente</th>
      <th>Hora</th>
      <th>Dia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.user_id %></td>
        <td><%= turno.paciente_id %></td>
        <td><%= turno.hora %></td>
        <td><%= turno.dia %></td>
        <td><%= link_to 'Show', turno %></td>
        <td><%= link_to 'Edit', edit_turno_path(turno) %></td>
        <td><%= link_to 'Destroy', turno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turno', new_turno_path %>

app/views/turnos/new.html.erb
<h1>New Turno</h1>

<%= render 'form' %>

<%= link_to 'Back', turnos_path %>

app/views/turnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id usuario:</strong>
  <%= @turno.user_id %>
</p>

<p>
  <strong>Id paciente:</strong>
  <%= @turno.paciente_id %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @turno.hora %>
</p>

<p>
  <strong>Dia:</strong>
  <%= @turno.dia %>
</p>

<%= link_to 'Edit', edit_turno_path(@turno) %> |
<%= link_to 'Back', turnos_path %>